apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\PC-A56\Documents\GitHub\ecommerce-project\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: php
  name: php
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: php
